version: '3'

services:
  game-server:
    image: game-server
    container_name: game-server
    restart: always
    volumes:
      - ./logs:/app/logs
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - INFURA_POLYGON_URL=${INFURA_POLYGON_URL}
      - INFURA_BSC_URL=${INFURA_BSC_URL} 