version: '3'

services:
  vrf-client:
    image: vrf-client
    container_name: vrf-client
    restart: always
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - INFURA_POLYGON_URL=${INFURA_POLYGON_URL}
      - INFURA_BSC_URL=${INFURA_BSC_URL} 