networks:
  primary:
    name: "polygon"
    rpc_url: "https://rpc-amoy.polygon.technology"
    contract_address: "0x743639440c8360212c277C974d80494a162Df7a9"
  fallback:
    name: "bnb"
    rpc_url: "https://data-seed-prebsc-2-s3.binance.org:8545"
    contract_address: "0xb921052b1b64cD12A3D4B6d51eFc0fa329E4A229"

vrf:
  num_words: 100
  gas_limit: 2500000
  confirmations: 3
  timeout: "5m"
  poll_interval: "5s"
  network_switch_timeout: "30s"

log:
  level: "info"
  format: "console"
  output: "stdout"