name: Deploy to EC2

on:
  push:
    branches: [ main ]  # 当推送到 main 分支时触发
  workflow_dispatch:    # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t vrf-client .
        docker save vrf-client > vrf-client.tar

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ec2-13-55-71-77.ap-southeast-2.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "vrf-client.tar,docker-compose.yml"
        target: "/home/ubuntu/vrf-client"

    - name: Start application
      uses: appleboy/ssh-action@master
      with:
        host: ec2-13-55-71-77.ap-southeast-2.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/vrf-client
          docker load < vrf-client.tar
          docker stop vrf-client || true
          docker rm vrf-client || true
          docker run -d \
            --name vrf-client \
            --restart always \
            -e PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}" \
            -e INFURA_POLYGON_URL="${{ secrets.INFURA_POLYGON_URL }}" \
            -e INFURA_BSC_URL="${{ secrets.INFURA_BSC_URL }}" \
            vrf-client
          docker image prune -f